v2/KoursProject/KoursProject/Controllers/AutosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using KoursProject.Data;
using KoursProject.Models;
using KoursProject.Models.Domain;

namespace KoursProject.Controllers
{
    public class AutosController : Controller
    {
        private readonly MVCProductDbContext mvcProductDbContext;

        public AutosController(MVCProductDbContext mvcProductDbContext)
        {
            this.mvcProductDbContext = mvcProductDbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var Autos = await mvcProductDbContext.Autos.ToListAsync();
            return View(Autos);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(AddAutosViewModel addAutosRequest)
        {
            var autos = new Autos()
            {
                Id = Guid.NewGuid(),
                Car = addAutosRequest.Car,
                Carnumber = addAutosRequest.Carnumber,
                Condition = addAutosRequest.Condition
            };

            await mvcProductDbContext.Autos.AddAsync(autos);
            await mvcProductDbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> View(Guid id)
        {
            var autos = await mvcProductDbContext.Autos.FirstOrDefaultAsync(x => x.Id == id);
            if (autos != null)
            {
                var viewModel = new UpdateAutosViewModel()
                {
                    Id = autos.Id,
                    Car = autos.Car,
                    Carnumber = autos.Carnumber,
                    Condition = autos.Condition
                };
                return await Task.Run(() => View("View", viewModel));
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> View(UpdateAutosViewModel model)
        {
            var autos = await mvcProductDbContext.Autos.FindAsync(model.Id);
            if (autos != null)
            {
                autos.Car = model.Car;
                autos.Carnumber = model.Carnumber;
                autos.Condition = model.Condition;

                await mvcProductDbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateAutosViewModel model)
        {
            var autos = await mvcProductDbContext.Autos.FindAsync(model.Id);

            if (autos != null)
            {
                mvcProductDbContext.Autos.Remove(autos);
                await mvcProductDbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

v2/KoursProject/KoursProject/Controllers/DriversController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using KoursProject.Data;
using KoursProject.Models;
using KoursProject.Models.Domain;

namespace KoursProject.Controllers
{
    public class DriversController : Controller
    {
        private readonly MVCProductDbContext mvcProductDbContext;

        public DriversController(MVCProductDbContext mvcProductDbContext)
        {
            this.mvcProductDbContext = mvcProductDbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var Drivers = await mvcProductDbContext.Drivers.ToListAsync();
            return View(Drivers);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(AddDriversViewModel addDriversRequest)
        {
            var drivers = new Drivers()
            {
                Id = Guid.NewGuid(),
                Surname = addDriversRequest.Surname,
                Name = addDriversRequest.Name,
                PhoneNumber = addDriversRequest.PhoneNumber,
                Email = addDriversRequest.Email,
                Address = addDriversRequest.Address,
                DateOfBirth = addDriversRequest.DateOfBirth
            };

            await mvcProductDbContext.Drivers.AddAsync(drivers);
            await mvcProductDbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> View(Guid id)
        {
            var drivers = await mvcProductDbContext.Drivers.FirstOrDefaultAsync(x => x.Id == id);
            if (drivers != null)
            {
                var viewModel = new UpdateDriversViewModel()
                {
                    Id = drivers.Id,
                    Surname = drivers.Surname,
                    Name = drivers.Name,
                    PhoneNumber = drivers.PhoneNumber,
                    Email = drivers.Email,
                    Address = drivers.Address,
                    DateOfBirth= drivers.DateOfBirth
                };
                return await Task.Run(() => View("View", viewModel));
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> View(UpdateDriversViewModel model)
        {
            var drivers = await mvcProductDbContext.Drivers.FindAsync(model.Id);
            if (drivers != null)
            {
                drivers.Surname = model.Surname;
                drivers.Name = model.Name;
                drivers.PhoneNumber = model.PhoneNumber;
                drivers.Email = model.Email;
                drivers.Address = model.Address;
                drivers.DateOfBirth= model.DateOfBirth;

                await mvcProductDbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateDriversViewModel model)
        {
            var drivers = await mvcProductDbContext.Drivers.FindAsync(model.Id);

            if (drivers != null)
            {
                mvcProductDbContext.Drivers.Remove(drivers);
                await mvcProductDbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

v2/KoursProject/KoursProject/Controllers/InvoicesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using KoursProject.Data;
using KoursProject.Models;
using KoursProject.Models.Domain;

namespace KoursProject.Controllers
{
    public class InvoicesController : Controller
    {
        private readonly MVCProductDbContext mvcProductDbContext;

        public InvoicesController(MVCProductDbContext mvcProductDbContext)
        {
            this.mvcProductDbContext = mvcProductDbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var Invoices = await mvcProductDbContext.Invoices.ToListAsync();
            return View(Invoices);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(AddInvoicesViewModel addInvoicesRequest)
        {
            var invoices = new Invoices()
            {
                Id = Guid.NewGuid(),
                InvoiceType = addInvoicesRequest.InvoiceType,
                Descrption = addInvoicesRequest.Descrption
            };

            await mvcProductDbContext.Invoices.AddAsync(invoices);
            await mvcProductDbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> View(Guid id)
        {
            var invoices = await mvcProductDbContext.Invoices.FirstOrDefaultAsync(x => x.Id == id);
            if (invoices != null)
            {
                var viewModel = new UpdateInvoicesViewModel()
                {
                    Id = invoices.Id,
                    InvoiceType = invoices.InvoiceType,
                    Descrption = invoices.Descrption
                };
                return await Task.Run(() => View("View", viewModel));
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> View(UpdateInvoicesViewModel model)
        {
            var invoices = await mvcProductDbContext.Invoices.FindAsync(model.Id);
            if (invoices != null)
            {
                invoices.InvoiceType = model.InvoiceType;
                invoices.Descrption = model.Descrption;

                await mvcProductDbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateInvoicesViewModel model)
        {
            var invoices = await mvcProductDbContext.Invoices.FindAsync(model.Id);

            if (invoices != null)
            {
                mvcProductDbContext.Invoices.Remove(invoices);
                await mvcProductDbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

v2/KoursProject/KoursProject/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using KoursProject.Data;
using KoursProject.Models;
using KoursProject.Models.Domain;

namespace KoursProject.Controllers
{
    public class OrderController : Controller
    {
        private readonly MVCProductDbContext mvcProductDbContext;

        public OrderController(MVCProductDbContext mvcProductDbContext)
        {
            this.mvcProductDbContext = mvcProductDbContext;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(mvcProductDbContext.Order
                .Include(rp=>rp.Products)
                .Include(rp=>rp.Autos)
                .Include(rp=>rp.Drivers)
                .Include(rp=>rp.Organizations)
                .Include(rp=>rp.Invoices)
                .ToList());
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(AddOrderViewModel addOrderRequest)
        {
            var order = new Order()
            {
                Id = Guid.NewGuid(),
                ProductsID = addOrderRequest.ProductsID,
                AutosID = addOrderRequest.AutosID,
                DriversId = addOrderRequest.DriversId,
                OrganizationsId = addOrderRequest.OrganizationsId,
                PhoneNumber= addOrderRequest.PhoneNumber,
                Address= addOrderRequest.Address,
                Data= addOrderRequest.Data,
                Email= addOrderRequest.Email,
                InvoicesId=addOrderRequest.InvoicesId
            };

            await mvcProductDbContext.Order.AddAsync(order);
            await mvcProductDbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> View(Guid id)
        {
            var order = await mvcProductDbContext.Order.FirstOrDefaultAsync(x => x.Id == id);
            if (order != null)
            {
                var viewModel = new UpdateOrderViewModel()
                {
                    Id = order.Id,
                    ProductsID = order.ProductsID,
                    AutosID = order.AutosID,
                    DriversId = order.DriversId,
                    OrganizationsId = order.OrganizationsId,
                    PhoneNumber = order.PhoneNumber,
                    Address = order.Address,
                    Data = order.Data,
                    Email = order.Email,
                    InvoicesId = order.InvoicesId
                };
                return await Task.Run(() => View("View", viewModel));
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> View(UpdateOrderViewModel model)
        {
            var order = await mvcProductDbContext.Order.FindAsync(model.Id);
            if (order != null)
            {
                order.ProductsID = model.ProductsID;
                order.AutosID = model.AutosID;
                order.DriversId = model.DriversId;
                order.OrganizationsId = model.OrganizationsId;
                order.PhoneNumber = model.PhoneNumber;
                order.Address = model.Address;
                order.Data = model.Data;
                order.Email = model.Email;
                order.InvoicesId = model.InvoicesId;

                await mvcProductDbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateOrderViewModel model)
        {
            var order = await mvcProductDbContext.Order.FindAsync(model.Id);

            if (order != null)
            {
                mvcProductDbContext.Order.Remove(order);
                await mvcProductDbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        }
}

v2/KoursProject/KoursProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KoursProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KoursProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">РосПродукт</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                    <!--    <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>-->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Заказы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Organizations" asp-action="Index">Организации</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Продукты</a>
                        </li>
                                                <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Autos" asp-action="Index">Автомобили</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Drivers" asp-action="Index">Водители</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Invoices" asp-action="Index">Накладные</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - KoursProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>